// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnvwuntgzyjajqfqqhpd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxudnd1bnRnenlqYWpxZnFxaHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MDUyMTMsImV4cCI6MjA1OTI4MTIxM30.sfWMrfs9MHX1Ll02lpkGWAttw57ojG2_o4ggvx9QQPw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);